#!/bin/bash

# test-quick-reference-edge-cases.sh
# Tests update-quick-reference.sh with edge case STATUS.md files
# Version: 5.1.0
#
# Tests:
# 1. Normal STATUS.md - should update successfully
# 2. STATUS.md without Quick Reference section - should gracefully skip
# 3. Empty STATUS.md - should gracefully skip
# 4. STATUS.md with Quick Reference at line 1 - should handle correctly
# 5. Missing config file - should exit with error

set -e

# Get the directory where this script lives
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 Testing update-quick-reference.sh Edge Cases"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Test counter
TESTS_PASSED=0
TESTS_FAILED=0

# Create temp test directory
TEST_DIR=$(mktemp -d)
echo "Test directory: $TEST_DIR"
echo ""

# Helper function for assertions
assert_exit_code() {
  local actual="$1"
  local expected="$2"
  local test_name="$3"

  if [ "$actual" -eq "$expected" ]; then
    echo -e "  ${GREEN}✅ PASS${NC}: $test_name (exit code $actual)"
    TESTS_PASSED=$((TESTS_PASSED + 1))
  else
    echo -e "  ${RED}❌ FAIL${NC}: $test_name"
    echo "    Expected exit code: $expected"
    echo "    Actual exit code:   $actual"
    TESTS_FAILED=$((TESTS_FAILED + 1))
  fi
}

assert_file_contains() {
  local file="$1"
  local pattern="$2"
  local test_name="$3"

  if grep -q "$pattern" "$file" 2>/dev/null; then
    echo -e "  ${GREEN}✅ PASS${NC}: $test_name"
    TESTS_PASSED=$((TESTS_PASSED + 1))
  else
    echo -e "  ${RED}❌ FAIL${NC}: $test_name"
    echo "    Pattern not found: $pattern"
    TESTS_FAILED=$((TESTS_FAILED + 1))
  fi
}

# =============================================================================
# Test 1: STATUS.md without Quick Reference section
# =============================================================================
echo "Test 1: STATUS.md without Quick Reference section"

# Create minimal context structure
mkdir -p "$TEST_DIR/test1/context"
cat > "$TEST_DIR/test1/context/.context-config.json" << 'CONFIGEOF'
{
  "version": "5.1.0",
  "project": {
    "name": "Test Project",
    "type": "web",
    "techStack": "Node.js",
    "urls": {
      "repository": "https://github.com/test/test"
    },
    "commands": {
      "dev": "npm run dev",
      "test": "npm test",
      "build": "npm run build"
    }
  }
}
CONFIGEOF

# STATUS.md without Quick Reference section
cat > "$TEST_DIR/test1/context/STATUS.md" << 'STATUSEOF'
# Project Status

**Status:** Active
**Phase:** Development

## Current Sprint

Working on features.

---

## History

Some history here.
STATUSEOF

# Run script (should exit 0, graceful skip)
cd "$TEST_DIR/test1"
EXIT_CODE=0
"$PROJECT_ROOT/scripts/update-quick-reference.sh" 2>/dev/null || EXIT_CODE=$?
assert_exit_code $EXIT_CODE 0 "Graceful skip when Quick Reference missing"

# =============================================================================
# Test 2: Empty STATUS.md
# =============================================================================
echo ""
echo "Test 2: Empty STATUS.md"

mkdir -p "$TEST_DIR/test2/context"
cp "$TEST_DIR/test1/context/.context-config.json" "$TEST_DIR/test2/context/"
> "$TEST_DIR/test2/context/STATUS.md"

cd "$TEST_DIR/test2"
EXIT_CODE=0
"$PROJECT_ROOT/scripts/update-quick-reference.sh" 2>/dev/null || EXIT_CODE=$?
assert_exit_code $EXIT_CODE 0 "Graceful skip when STATUS.md is empty"

# =============================================================================
# Test 3: Normal STATUS.md with Quick Reference section
# =============================================================================
echo ""
echo "Test 3: Normal STATUS.md with Quick Reference section"

mkdir -p "$TEST_DIR/test3/context"
cp "$TEST_DIR/test1/context/.context-config.json" "$TEST_DIR/test3/context/"

cat > "$TEST_DIR/test3/context/STATUS.md" << 'STATUSEOF'
# Project Status

**Status:** 🟢 Active
**Phase:** Development

## 📊 Quick Reference
_(This section is auto-generated by /save and /save-full - DO NOT edit manually)_

**Project:** Old Name
**Phase:** Old Phase

---

## Current Sprint

Working on features.

---

## History

Some history here.
STATUSEOF

cd "$TEST_DIR/test3"
EXIT_CODE=0
"$PROJECT_ROOT/scripts/update-quick-reference.sh" 2>/dev/null || EXIT_CODE=$?
assert_exit_code $EXIT_CODE 0 "Successfully updates normal STATUS.md"
assert_file_contains "$TEST_DIR/test3/context/STATUS.md" "Test Project" "Quick Reference contains updated project name"

# =============================================================================
# Test 4: STATUS.md with Quick Reference at line 1
# =============================================================================
echo ""
echo "Test 4: STATUS.md with Quick Reference at line 1"

mkdir -p "$TEST_DIR/test4/context"
cp "$TEST_DIR/test1/context/.context-config.json" "$TEST_DIR/test4/context/"

cat > "$TEST_DIR/test4/context/STATUS.md" << 'STATUSEOF'
## 📊 Quick Reference
_(This section is auto-generated)_

**Project:** Test

---

## Rest of file
STATUSEOF

cd "$TEST_DIR/test4"
EXIT_CODE=0
"$PROJECT_ROOT/scripts/update-quick-reference.sh" 2>/dev/null || EXIT_CODE=$?
assert_exit_code $EXIT_CODE 0 "Handles Quick Reference at line 1"

# =============================================================================
# Test 5: Missing config file
# =============================================================================
echo ""
echo "Test 5: Missing config file"

mkdir -p "$TEST_DIR/test5/context"
cat > "$TEST_DIR/test5/context/STATUS.md" << 'STATUSEOF'
# Status
## 📊 Quick Reference
Test
---
STATUSEOF

cd "$TEST_DIR/test5"
EXIT_CODE=0
"$PROJECT_ROOT/scripts/update-quick-reference.sh" 2>/dev/null || EXIT_CODE=$?
# Should exit with error (EXIT_NOT_FOUND = 3 or EXIT_ERROR = 1)
if [ $EXIT_CODE -ne 0 ]; then
  echo -e "  ${GREEN}✅ PASS${NC}: Exits with error when config missing (exit code $EXIT_CODE)"
  TESTS_PASSED=$((TESTS_PASSED + 1))
else
  echo -e "  ${RED}❌ FAIL${NC}: Should exit with error when config missing"
  TESTS_FAILED=$((TESTS_FAILED + 1))
fi

# =============================================================================
# Cleanup
# =============================================================================
rm -rf "$TEST_DIR"

# =============================================================================
# Summary
# =============================================================================
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test Summary"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo -e "  Passed: ${GREEN}$TESTS_PASSED${NC}"
echo -e "  Failed: ${RED}$TESTS_FAILED${NC}"
echo ""

if [ $TESTS_FAILED -eq 0 ]; then
  echo -e "${GREEN}✅ All tests passed!${NC}"
  exit 0
else
  echo -e "${RED}❌ Some tests failed!${NC}"
  exit 1
fi
